### ISSUE TITLE
Replace the current custom ACI sdk with the official Azure ACI SDK 

### ISSUE THREAD

**Issue by helayoty** [virtual-kubelet/azure-aci#203]
Since Azure Go SDK has been introduced, we need to replace the custom SDK in the current code with Azure [SDK](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/containerinstance/armcontainerinstance).

- [x] Add SDK new dependencies #281  
-  [x] Migrate provider package and all tests related
     - [x] Migrate Auth #299 
     - [x] Migrate Client #301 
     - [x] Migrate log analytics #300 
     - [x] Migrate metrics #315 
     - [x] Implement API mocks #316 
     - [x] Update `main.go` and implement switch between old and new implementation #318 
- [x] Remove/Delete custom SDK
     - [x] Delete client, provider folders #482
     - [x] Update helm chart and pipelines
