### ISSUE TITLE
Migrate to Azure SDK v2

### ISSUE THREAD

**Issue by helayoty** [virtual-kubelet/azure-aci#414]
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/containerinstance/armcontainerinstance

- [x] Replace with new ACI SDK #422 
- [x] Replace with new network SDK #424
- [x] Remove the custom code that was used by V1 #423
