### ISSUE TITLE
Add unit tests for real_time.go

### ISSUE THREAD

**Issue by nidhunge** [virtual-kubelet/azure-aci#514]
There are no unit tests for real_time.go file. 

- [x] Create and add real_time_test.go file #515
- [x]  Add Unit Test for calculateUsageNanoCores #515
- [x] Bugfix for edge scenarios when uint64 values used are negative or very low in real_time.go #515
- [x] Bugfix for pointer reference where the pointer jumped to next object even if the "If" condition wasn't valid in a for loop. #515
- [x] Add Unit Test for filterOutContainerNotInPod #526 
- [x] Add Unit Test for getRealTimeExtensionPodStats #531 
- [x] Add Unit Test for extensionPodStatsToKubeletPodStats #534 
- [x] Bugfix for extensionPodStatsToKubeletPodStats where pointers jumped inside for range loops and assigned the same value as the last item in range for all values.#534
